CREATE ROLE webadmin;
CREATE TABLESPACE tbs_bd_112 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_112';
CREATE TABLESPACE tbs_bd_21 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_21';
CREATE TABLESPACE tbs_bd_103 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_103';
CREATE TABLESPACE tbs_bd_125 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_125';
CREATE TABLESPACE tbs_bd_111 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_111';
CREATE TABLESPACE tbs_bd_117 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_117';
CREATE TABLESPACE tbs_bd_13 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_13';
CREATE TABLESPACE tbs_bd_137 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_137';
CREATE TABLESPACE tbs_bd_22 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_22';
CREATE TABLESPACE tbs_bd_23 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_23';
CREATE TABLESPACE tbs_bd_47 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_47';
CREATE TABLESPACE tbs_bd_55 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_55';
CREATE TABLESPACE tbs_bd_5 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_5';
CREATE TABLESPACE tbs_bd_71 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_71';
CREATE TABLESPACE tbs_bd_63 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_63';
CREATE TABLESPACE tbs_bd_79 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_79';
CREATE TABLESPACE tbs_bd_87 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_87';
CREATE TABLESPACE tbs_bd_95 OWNER webadmin LOCATION '/data/pgsql/dsn_ts/bd_95';
CREATE DATABASE dsn OWNER webadmin;
